/** @type {import('tailwindcss').Config} */
const c = (name) => `var(--${name})`;

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', "system-ui", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      colors: {
        bg: c("bg"),
        surface: c("surface"),
        "surface-2": c("surface-2"),
        border: c("border"),
        "border-2": c("border-2"),
        line: c("line"),
        hover: c("hover"),
        text: c("text"),
        "text-2": c("text-2"),
        "text-3": c("text-3"),
        muted: c("muted"),
        faint: c("faint"),
        dvf: c("dvf"),
        accent: c("accent"),
        "accent-hover": c("accent-hover"),
        "accent-text": c("accent-text"),
        "accent-tint": c("accent-tint"),
        "accent-border": c("accent-border"),
        "ink-bg": c("ink-bg"),
        "ink-fg": c("ink-fg"),
        "toast-bg": c("toast-bg"),
        ok: c("ok"),
        "ok-bg": c("ok-bg"),
        "btn-ok": c("btn-ok"),
        info: c("info"),
        "info-bg": c("info-bg"),
        purple: c("purple"),
        "purple-bg": c("purple-bg"),
        warn: c("warn"),
        "warn-bg": c("warn-bg"),
        danger: c("danger"),
        "danger-bg": c("danger-bg"),
        nbg: c("nbg"),
        nfg: c("nfg"),
        "abandon-border": c("abandon-border"),
        "c-green": c("c-green"),
        "c-amber": c("c-amber"),
        "c-red": c("c-red"),
        "donut-track": c("donut-track"),
      },
    },
  },
  plugins: [],
};
